name = "UnregisteredExample"
uuid = "52f0ff55-7534-4748-86b3-12fe8f25fd1a"
authors = ["Peter Goodall <pjgoodall@gmail.com>"]
julia = "1.6.3"
version = "0.1.0"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"

[compat]
julia = "^1.6.3"
Example = "^0.5.3"
